sudo: false
language: ruby
rvm:
  - 2.5.0
before_install: gem install bundler -v 1.16.1
before_script:
  - bundle install
script: bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: always
